version: '3'

services:                         # ← ★ ここが必須 ★
  # ------------------------------- 
  # Cloud SQL Auth Proxy
  # -------------------------------
  cloud-sql-proxy:
    image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.10.1
    command: >
      --address 0.0.0.0
      --port 5432
      --credentials-file /config/adc.json
      term7-futa-sato:us-central1:gmail-ai-db
    volumes:
      - ./adc.json:/config/adc.json:ro
    restart: unless-stopped

  # -------------------------------
  # FastAPI アプリ
  # -------------------------------
  demo-app:
    build:
      context: ../backend
      dockerfile: Dockerfile
    env_file:
      - ../backend/.env.local
    depends_on:
      - cloud-sql-proxy
    volumes:
      - .dockervenv:/src/.venv
      - .:/src
    environment:
      DB_HOST: cloud-sql-proxy
    ports:
      - "8000:8000"
