version: "3.9"
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: gmailai
      POSTGRES_PASSWORD: gmailai
      POSTGRES_DB: gmailai
    ports: ["5432:5432"]

  redis:
    image: redis:7
    ports: ["6379:6379"]

  backend:
    build:
      context: ../backend
      dockerfile: ../infra/Dockerfile.backend
    env_file: ../backend/.env
    ports: ["8000:8000"]
    depends_on: [postgres, redis]

  worker:
    build:
      context: ../backend
      dockerfile: ../infra/Dockerfile.worker
    env_file: ../backend/.env
    depends_on: [postgres, redis]
